[package]
name = "cosmic-term"
version = "1.9.0"
description = "COSMIC Terminal"
license = "GPL-3.0-only"
homepage = "https://github.com/pop-os/cosmic-term"

[[source]]
url = "https://github.com/pop-os/cosmic-term/archive/refs/tags/epoch-1.9.0.tar.gz"
sha256 = "2e5ef9ff8428503024f84e9d0c9d8b0007dec0be42b398e5925d209ec91e2e19"

[depends]
build = ["toolchain", "stage1-rust", "just", "libxkbcommon", "wayland"]
run = ["glibc", "gcc", "wayland", "mesa", "libxkbcommon"]

[build]
vendor = "cargo"
script = """
export VERGEN_GIT_SHA="epoch-1.9.0"
export VERGEN_GIT_COMMIT_DATE="$(date -u -d "@$SOURCE_DATE_EPOCH" +%Y-%m-%d)"
cargo build --release --frozen
just rootdir=/ prefix=/usr install
"""
