[package]
name = "cosmic-panel"
version = "1.9.0"
description = "COSMIC panel and dock"
license = "GPL-3.0-only"
homepage = "https://github.com/pop-os/cosmic-panel"

[[source]]
url = "https://github.com/pop-os/cosmic-panel/archive/refs/tags/epoch-1.9.0.tar.gz"
sha256 = "6b036076e162568b6d0230ab82916b30d06b4942cb5be6a39960e42b499cab9b"

[depends]
build = ["toolchain", "stage1-rust", "just", "mesa", "libxkbcommon", "wayland"]
run = ["glibc", "gcc", "wayland", "mesa", "libxkbcommon"]

[build]
vendor = "cargo"
script = """
export VERGEN_GIT_SHA="epoch-1.9.0"
export VERGEN_GIT_COMMIT_DATE="$(date -u -d "@$SOURCE_DATE_EPOCH" +%Y-%m-%d)"
cargo build --release --frozen
just rootdir=/ prefix=/usr install
"""
