[package]
name = "cosmic-osk"
version = "1.9.0"
description = "COSMIC on-screen keyboard"
license = "GPL-3.0-only"
homepage = "https://github.com/pop-os/cosmic-osk"

[[source]]
url = "https://github.com/pop-os/cosmic-osk/archive/refs/tags/epoch-1.9.0.tar.gz"
sha256 = "6a4095f0474d55ecefe0e1f4bb24f5a7bffdf0450e87de40c668da1d628bd1f6"

[depends]
build = ["toolchain", "stage1-rust", "just", "eudev", "libxkbcommon", "wayland"]
run = ["glibc", "gcc", "wayland", "mesa", "libxkbcommon", "eudev"]

[build]
vendor = "cargo"
script = """
export VERGEN_GIT_SHA="epoch-1.9.0"
export VERGEN_GIT_COMMIT_DATE="$(date -u -d "@$SOURCE_DATE_EPOCH" +%Y-%m-%d)"
cargo build --release --frozen
just rootdir=/ prefix=/usr install
"""
