[package]
name = "cosmic-randr"
version = "1.9.0"
description = "COSMIC display configuration tool"
license = "GPL-3.0-only"
homepage = "https://github.com/pop-os/cosmic-randr"

[[source]]
url = "https://github.com/pop-os/cosmic-randr/archive/refs/tags/epoch-1.9.0.tar.gz"
sha256 = "6c082cba6b80c5d89b02aec7ed315c9de8452cd413f5181ece43d7fdb3011481"

[depends]
build = ["toolchain", "stage1-rust", "just"]
run = ["glibc", "gcc"]

[build]
vendor = "cargo"
script = """
export VERGEN_GIT_SHA="epoch-1.9.0"
export VERGEN_GIT_COMMIT_DATE="$(date -u -d "@$SOURCE_DATE_EPOCH" +%Y-%m-%d)"
cargo build --release --frozen
just rootdir=/ prefix=/usr install
"""
