[package]
name = "cosmic-app-library"
version = "1.9.0"
description = "COSMIC application library"
license = "GPL-3.0-only"
homepage = "https://github.com/pop-os/cosmic-app-library"

[[source]]
url = "https://github.com/pop-os/cosmic-app-library/archive/refs/tags/epoch-1.9.0.tar.gz"
sha256 = "d85fb7648429bb3319dc1f1dd69f510019d4f5815be93c42a3f57f2211abe740"

[depends]
build = ["toolchain", "stage1-rust", "just", "libxkbcommon", "wayland"]
run = ["glibc", "gcc", "wayland", "mesa", "libxkbcommon"]

[build]
vendor = "cargo"
script = """
export VERGEN_GIT_SHA="epoch-1.9.0"
export VERGEN_GIT_COMMIT_DATE="$(date -u -d "@$SOURCE_DATE_EPOCH" +%Y-%m-%d)"
cargo build --release --frozen
just rootdir=/ prefix=/usr install
"""
