[package]
name = "alsa-lib"
version = "1.2.16.1"
description = "ALSA library"
license = "LGPL-2.1-or-later"
homepage = "https://www.alsa-project.org"

[[source]]
url = "https://www.alsa-project.org/files/pub/lib/alsa-lib-1.2.16.1.tar.bz2"
sha256 = "f740db7f488255944ffd4428416ee3390a96742856916433df468c281436480e"

[depends]
build = ["toolchain"]
run = ["glibc"]

[build]
script = """
./configure \\
    --prefix=/usr \\
    --build="$TARGET" \\
    --sysconfdir=/etc \\
    --localstatedir=/var \\
    --disable-static \\
    --without-debug \\
    --disable-python
make -j"$JOBS"
make install
"""
