[package]
name = "libevdev"
version = "1.13.7"
description = "Input event device library"
license = "MIT"
homepage = "https://www.freedesktop.org/wiki/Software/libevdev/"

[[source]]
url = "https://www.freedesktop.org/software/libevdev/libevdev-1.13.7.tar.xz"
sha256 = "0caf824971108f15bb2ad356433bae198d7d3bf1e82d43f63626e069e060bfa6"

[depends]
build = ["buildtools"]
run = ["glibc"]

[build]
script = """
meson setup build . \\
    --prefix=/usr \\
    --libdir=lib \\
    --sysconfdir=/etc \\
    --localstatedir=/var \\
    --buildtype=release \\
    --wrap-mode=nodownload \\
    -Dtests=disabled \\
    -Ddocumentation=disabled
meson compile -C build -j "$JOBS"
meson install -C build
"""
