[package]
name = "libpng"
version = "1.6.59"
description = "PNG library"
license = "libpng-2.0"
homepage = "http://www.libpng.org/pub/png/libpng.html"

[[source]]
url = "https://download.sourceforge.net/libpng/libpng-1.6.59.tar.xz"
sha256 = "d80dd2a38a37f803cb9b6ac7b14bd6e74ddc3b654780a8380bdf93523fdb4389"

[depends]
build = ["toolchain"]
run = ["glibc", "zlib"]

[build]
script = """
./configure \\
    --prefix=/usr \\
    --build="$TARGET" \\
    --sysconfdir=/etc \\
    --localstatedir=/var \\
    --disable-static
make -j"$JOBS"
make install
"""
