[package]
name = "diffutils"
version = "3.12"
description = "diff, cmp and patch's companions"
license = "GPL-3.0-or-later"
homepage = "https://www.gnu.org/software/diffutils/"

[[source]]
url = "https://ftp.gnu.org/gnu/diffutils/diffutils-3.12.tar.xz"
sha256 = "7c8b7f9fc8609141fdea9cece85249d308624391ff61dedaf528fcb337727dfd"

[depends]
build = ["toolchain"]
run = ["glibc"]

[build]
script = """
./configure \\
    --prefix=/usr \\
    --build="$TARGET" \\
    --sysconfdir=/etc \\
    --localstatedir=/var \\
    --disable-static
make -j"$JOBS"
make install
"""
