[package]
name = "expat"
version = "2.8.5"
description = "XML parser library"
license = "MIT"
homepage = "https://libexpat.github.io"

[[source]]
url = "https://github.com/libexpat/libexpat/releases/download/R_2_8_5/expat-2.8.5.tar.xz"
sha256 = "1e727b8933ec51a77a9a9d9afcf8e688bce45d907c13e36ab7393fe36e703182"

[depends]
build = ["toolchain"]
run = ["glibc"]

[build]
script = """
./configure \\
    --prefix=/usr \\
    --build="$TARGET" \\
    --sysconfdir=/etc \\
    --localstatedir=/var \\
    --disable-static \\
    --without-docbook \\
    --without-examples \\
    --without-tests
make -j"$JOBS"
make install
"""
