[package]
name = "sed"
version = "4.10"
description = "Stream editor"
license = "GPL-3.0-or-later"
homepage = "https://www.gnu.org/software/sed/"

[[source]]
url = "https://ftp.gnu.org/gnu/sed/sed-4.10.tar.xz"
sha256 = "b8e72182b2ec96a3574e2998c47b7aaa64cc20ce000d8e9ac313cc07cecf28c7"

[depends]
build = ["toolchain"]
run = ["glibc"]

[build]
script = """
./configure \\
    --prefix=/usr \\
    --build="$TARGET" \\
    --sysconfdir=/etc \\
    --localstatedir=/var \\
    --disable-static
make -j"$JOBS"
make install
"""
