//! `hide install`: put a payload on a disk. See ARCHITECTURE.md, "Disk
//! layout" and "Disk images are installed, not assembled".
//!
//! The same code installs hideOS on a real machine (H7) and writes the disk
//! images the build produces, by running as PID 1 of hideOS Minimal in QEMU.
//! So it handles being PID 1: it mounts what it needs, and powers off when
//! asked rather than exiting, which would panic the kernel.

use std::fs;
use std::io::Read;
use std::os::fd::AsFd;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::thread;
use std::time::{Duration, Instant};

use anyhow::{Context, Result, bail, ensure};
use composefs_ioctls::fsverity::{EnableVerityError, fs_ioc_enable_verity, fs_ioc_measure_verity};
use rustix::fs::{Mode, OFlags};
use rustix::mount::{MountFlags, UnmountFlags, mount, unmount};

/// GPT partition type GUIDs, from the Discoverable Partitions Specification.
const ESP_TYPE: &str = "C12A7328-F81F-11D2-BA4B-00A0C93EC93B";
fn root_type() -> &'static str {
    if cfg!(target_arch = "aarch64") {
        "B921B045-1DF0-41C3-AF44-4C6F280D3FAE"
    } else {
        "4F68BCE3-E8CD-4DB1-96E7-FBCAF984B709"
    }
}
/// Partition names hidestage looks for.
const ESP_NAME: &str = "hideos-esp";
const ROOT_NAME: &str = "hideos-root";
/// Subvolumes on the root partition. See ARCHITECTURE.md, "Disk layout".
const SUBVOLUMES: &[&str] = &["@store", "@etc", "@var", "@home"];
/// Where the payload's top-level directories go.
const PAYLOAD_DIRS: &[(&str, &str)] = &[("repo", "@store"), ("etc", "@etc")];
const WORK: &str = "/run/hide-install";
/// fs-verity: SHA-256 over 4 KiB blocks, what composefs repositories use.
const VERITY_SHA256: u8 = 1;
const VERITY_BLOCK: u32 = 4096;
/// The kernel starts PID 1 with no PATH, so the tools are looked up here
/// rather than in the environment. Merged /usr: everything is in /usr/bin.
const PATH: &str = "/usr/bin:/usr/sbin";

pub(crate) struct Options {
    pub(crate) payload: PathBuf,
    pub(crate) disk: PathBuf,
    pub(crate) poweroff: bool,
    /// The first account, `NAME` and password. Without one, the machine has
    /// only root, with no password: fine for Minimal at a console, not for
    /// a greeter.
    pub(crate) user: Option<(String, String)>,
    /// The passphrase the root is encrypted with, LUKS2; none for an
    /// unencrypted root. The TPM seals the key at the first boot that has
    /// one: see `hide tpm-enroll`.
    pub(crate) encrypt: Option<String>,
    /// A second passphrase for the encrypted root, generated by the
    /// installer and shown once: what opens the disk when the first is
    /// forgotten and the TPM cannot.
    pub(crate) recovery_key: Option<String>,
    /// The swap file, in MiB: as large as memory when not given, which is
    /// what hibernation needs. 0 for none. Read at install time: as PID 1,
    /// /proc is not mounted while the arguments are parsed.
    pub(crate) swap_mib: Option<u64>,
    /// A reinstall: the partitions, the encryption and @home are kept;
    /// the ESP and every other subvolume are made anew. What a person
    /// whose system no longer starts, or who wants a clean one, does
    /// without losing their files.
    pub(crate) keep_home: bool,
}

pub fn run(args: &[String]) -> Result<()> {
    let options = parse(args)?;
    let pid1 = rustix::process::getpid().is_init();
    if pid1 {
        mount_pseudo_filesystems()?;
    }
    let result = install(&options);
    if let Err(error) = &result {
        eprintln!("hide install: FAILED: {error:#}");
    }
    if pid1 || options.poweroff {
        // PID 1 cannot exit. Whatever happened has been said; power off, and
        // whoever started the machine reads the console.
        rustix::fs::sync();
        let _ = rustix::system::reboot(rustix::system::RebootCommand::PowerOff);
    }
    result
}

fn parse(args: &[String]) -> Result<Options> {
    let mut payload = None;
    let mut disk = None;
    let mut poweroff = false;
    let mut user = None;
    let mut password = None;
    let mut swap_mib = None;
    let mut encrypt = None;
    let mut keep_home = false;
    let mut iter = args.iter();
    while let Some(arg) = iter.next() {
        match arg.as_str() {
            "--payload" => payload = iter.next().map(PathBuf::from),
            "--disk" => disk = iter.next().map(PathBuf::from),
            "--poweroff" => poweroff = true,
            "--keep-home" => keep_home = true,
            "--user" => user = iter.next().cloned(),
            // On the command line, so only for disks made for development:
            // the installer proper asks for it.
            "--password" => password = iter.next().cloned(),
            // On the command line, like --password: development disks only.
            "--encrypt" => encrypt = iter.next().cloned(),
            "--swap" => {
                let value = iter.next().context("--swap takes a size in MiB")?;
                swap_mib = Some(value.parse().context("--swap takes a size in MiB")?);
            }
            other => bail!("unknown argument `{other}`"),
        }
    }
    let user = match (user, password) {
        (Some(name), Some(password)) => Some((name, password)),
        (None, None) => None,
        _ => bail!("--user and --password go together"),
    };
    Ok(Options {
        payload: payload.context("--payload FILE is required")?,
        disk: disk.context("--disk DEVICE is required")?,
        poweroff,
        user,
        encrypt,
        recovery_key: None,
        swap_mib,
        keep_home,
    })
}

pub(crate) fn install(options: &Options) -> Result<()> {
    let disk = &options.disk;
    let (esp, partition_2) = if options.keep_home {
        say(&format!(
            "reinstalling on {}, keeping /home",
            disk.display()
        ));
        let esp = partition_on(disk, ESP_NAME)
            .with_context(|| format!("{} has no {ESP_NAME} partition", disk.display()))?;
        let root = partition_on(disk, ROOT_NAME)
            .with_context(|| format!("{} has no {ROOT_NAME} partition", disk.display()))?;
        ensure!(
            options.encrypt.is_some() || !is_luks(&root),
            "the root is encrypted: its passphrase is needed to keep /home"
        );
        (esp, root)
    } else {
        say(&format!("partitioning {}", disk.display()));
        partition(disk)?;
        (wait_for_partition(disk, 1)?, wait_for_partition(disk, 2)?)
    };
    let root = match &options.encrypt {
        Some(passphrase) => {
            if !options.keep_home {
                say("encrypting the root, LUKS2");
                with_stdin(
                    tool("cryptsetup")
                        .args(["luksFormat", "--type", "luks2", "--batch-mode"])
                        .args(["--label", "hideos", "--key-file=-"])
                        .arg(&partition_2),
                    passphrase,
                )?;
            }
            with_stdin(
                tool("cryptsetup")
                    .args(["open", "--key-file=-"])
                    .arg(&partition_2)
                    .arg(MAPPED_NAME),
                passphrase,
            )?;
            // A reinstall keeps the keyslots: the recovery key a person
            // wrote down still opens the disk.
            if let Some(recovery) = options.recovery_key.as_ref().filter(|_| !options.keep_home) {
                add_key(&partition_2, passphrase, recovery)?;
                say("recovery key added");
            }
            Path::new("/dev/mapper").join(MAPPED_NAME)
        }
        None => partition_2,
    };

    say("creating filesystems");
    exec(
        tool("mkfs.vfat")
            .args(["-F", "32", "-n", "HIDEOS-ESP"])
            .arg(&esp),
    )?;
    if !options.keep_home {
        exec(
            tool("mkfs.btrfs")
                .args(["-f", "-q", "-L", "hideos"])
                .arg(&root),
        )?;
    }

    let root_mount = Path::new(WORK).join("root");
    let esp_mount = Path::new(WORK).join("esp");
    fs::create_dir_all(&root_mount)?;
    fs::create_dir_all(&esp_mount)?;
    // The top level, where the subvolumes are, whatever the default is.
    mount(
        &root,
        &root_mount,
        "btrfs",
        MountFlags::NOATIME,
        Some(c"subvolid=5"),
    )
    .with_context(|| format!("mounting {}", root.display()))?;
    // quiet: FAT has no permissions, and without it the chmods unpacking
    // makes are errors rather than no-ops.
    mount(
        &esp,
        &esp_mount,
        "vfat",
        MountFlags::empty(),
        Some(c"quiet"),
    )
    .with_context(|| format!("mounting {}", esp.display()))?;
    if options.keep_home {
        // Everything but @home goes, @swap too: a swap file kept could hold
        // a hibernated system that is no longer there to resume.
        // --recursive: @var can hold subvolumes of its own, made by
        // container storage.
        for subvolume in ["@store", "@etc", "@var", "@swap"] {
            let path = root_mount.join(subvolume);
            if path.exists() {
                exec(
                    tool("btrfs")
                        .args(["-q", "subvolume", "delete", "--recursive"])
                        .arg(&path),
                )?;
            }
        }
        say("the old system removed; @home kept");
    }
    for subvolume in SUBVOLUMES {
        if root_mount.join(subvolume).exists() {
            continue;
        }
        exec(
            tool("btrfs")
                .args(["-q", "subvolume", "create"])
                .arg(root_mount.join(subvolume)),
        )?;
    }

    let swap_mib = match options.swap_mib {
        Some(mib) => mib,
        None => memory_mib()?,
    };
    if swap_mib > 0 {
        let swap = root_mount.join("@swap");
        exec(tool("btrfs").args(["-q", "subvolume", "create"]).arg(&swap))?;
        // mkswapfile makes the file as swap needs it on btrfs: no copy on
        // write, no compression, allocated in full.
        exec(
            tool("btrfs")
                .args(["-q", "filesystem", "mkswapfile", "--size"])
                .arg(format!("{swap_mib}m"))
                .arg(swap.join("swapfile")),
        )?;
        say(&format!("swap file of {swap_mib} MiB"));
    }

    say(&format!("unpacking {}", options.payload.display()));
    let digest = unpack(&options.payload, &root_mount, &esp_mount)?;

    say("enabling fs-verity on every object");
    let objects = root_mount.join("@store/objects");
    let count = enable_verity(&objects)?;
    // meta.json sealed too: composefs then opens the store as one that
    // requires fs-verity, and seals every object an update writes.
    seal(&root_mount.join("@store/meta.json"))?;
    say(&format!("  {count} objects sealed"));

    // The check hidestage makes at every boot, made once here, so that a
    // payload that would not boot is a failed install, not a failed boot.
    let image = root_mount.join("@store/images").join(&digest);
    let file = rustix::fs::open(&image, OFlags::RDONLY | OFlags::CLOEXEC, Mode::empty())
        .with_context(|| format!("opening {}", image.display()))?;
    let measured: [u8; 32] = fs_ioc_measure_verity(file.as_fd(), VERITY_SHA256)
        .map_err(|e| anyhow::anyhow!("measuring the image: {e}"))?;
    // Closed now: an open file keeps the filesystem from unmounting.
    drop(file);
    ensure!(
        hex(&measured) == digest,
        "the image measures sha256:{}, but the payload says sha256:{digest}",
        hex(&measured)
    );
    say(&format!("image sealed: sha256:{digest}"));

    if let Some((name, password)) = &options.user {
        add_user(&root_mount, name, password)?;
        say(&format!("user {name} created"));
    }

    rustix::fs::sync();
    unmount(&esp_mount, UnmountFlags::empty()).context("unmounting the ESP")?;
    unmount(&root_mount, UnmountFlags::empty()).context("unmounting the root")?;
    if options.encrypt.is_some() {
        exec(tool("cryptsetup").args(["close", MAPPED_NAME]))?;
    }
    say("installed");
    Ok(())
}

/// A GPT with the ESP first and the root after it, filling the disk. Names
/// and types are what hidestage and the firmware look for.
fn partition(disk: &Path) -> Result<()> {
    let script = format!(
        "label: gpt\n\
         size=512MiB, type={ESP_TYPE}, name=\"{ESP_NAME}\"\n\
         type={}, name=\"{ROOT_NAME}\"\n",
        root_type()
    );
    let mut child = tool("sfdisk")
        .args(["--quiet", "--wipe", "always", "--wipe-partitions", "always"])
        .arg(disk)
        .stdin(Stdio::piped())
        .spawn()
        .context("running sfdisk")?;
    use std::io::Write;
    child
        .stdin
        .take()
        .context("sfdisk's stdin")?
        .write_all(script.as_bytes())?;
    ensure!(
        child.wait()?.success(),
        "sfdisk failed on {}",
        disk.display()
    );
    Ok(())
}

/// The partition of `disk` named `label`, from sysfs, which lists a disk's
/// partitions under it.
pub(crate) fn partition_on(disk: &Path, label: &str) -> Option<PathBuf> {
    let name = disk.file_name()?.to_string_lossy().into_owned();
    for entry in fs::read_dir(Path::new("/sys/block").join(&name))
        .ok()?
        .flatten()
    {
        let uevent = fs::read_to_string(entry.path().join("uevent")).unwrap_or_default();
        let field = |key: &str| uevent.lines().find_map(|l| l.strip_prefix(key));
        if field("PARTNAME=") == Some(label)
            && let Some(dev) = field("DEVNAME=")
        {
            return Some(Path::new("/dev").join(dev));
        }
    }
    None
}

pub(crate) fn is_luks(device: &Path) -> bool {
    tool("cryptsetup")
        .arg("isLuks")
        .arg(device)
        .status()
        .is_ok_and(|s| s.success())
}

/// Whether `passphrase` opens the LUKS2 `device`, without opening it.
pub(crate) fn opens(device: &Path, passphrase: &str) -> bool {
    with_stdin(
        tool("cryptsetup")
            .args(["open", "--test-passphrase", "--key-file=-"])
            .arg(device),
        passphrase,
    )
    .is_ok()
}

/// The device node of partition `number` of `disk`, once the kernel has
/// created it: `/dev/vda` → `/dev/vda1`, `/dev/nvme0n1` → `/dev/nvme0n1p1`.
fn wait_for_partition(disk: &Path, number: u32) -> Result<PathBuf> {
    let name = disk.to_string_lossy();
    let separator = if name.ends_with(|c: char| c.is_ascii_digit()) {
        "p"
    } else {
        ""
    };
    let path = PathBuf::from(format!("{name}{separator}{number}"));
    let started = Instant::now();
    while !path.exists() {
        ensure!(
            started.elapsed() < Duration::from_secs(10),
            "{} did not appear after partitioning",
            path.display()
        );
        thread::sleep(Duration::from_millis(100));
    }
    Ok(path)
}

/// Extracts the payload: `repo/` into @store, `etc/` into @etc, `esp/` onto
/// the ESP. Returns the image digest from `image.digest`.
fn unpack(payload: &Path, root: &Path, esp: &Path) -> Result<String> {
    let file = fs::File::open(payload).with_context(|| format!("opening {}", payload.display()))?;
    let mut archive = tar::Archive::new(file);
    archive.set_preserve_permissions(true);
    archive.set_preserve_mtime(true);
    archive.set_unpack_xattrs(true);
    let mut digest = None;
    for entry in archive.entries()? {
        let mut entry = entry?;
        let path = entry.path()?.into_owned();
        let mut components = path.components();
        let top = components
            .next()
            .map(|c| c.as_os_str().to_string_lossy().into_owned())
            .unwrap_or_default();
        let rest: PathBuf = components.collect();
        if top == "image.digest" {
            let mut text = String::new();
            entry.read_to_string(&mut text)?;
            digest = Some(
                text.trim()
                    .strip_prefix("sha256:")
                    .context("image.digest is not sha256:<hex>")?
                    .to_owned(),
            );
            continue;
        }
        let base = match top.as_str() {
            "esp" => esp.to_path_buf(),
            other => match PAYLOAD_DIRS.iter().find(|(dir, _)| *dir == other) {
                Some((_, subvolume)) => root.join(subvolume),
                None => bail!("unexpected `{}` in the payload", path.display()),
            },
        };
        if rest.as_os_str().is_empty() {
            continue;
        }
        let target = base.join(&rest);
        if let Some(parent) = target.parent() {
            fs::create_dir_all(parent)?;
        }
        entry
            .unpack(&target)
            .with_context(|| format!("unpacking {}", path.display()))?;
    }
    digest.context("the payload has no image.digest")
}

/// Enables fs-verity on every regular file under `objects`. Each file must
/// be closed for writing, which, freshly unpacked and synced, they are.
fn enable_verity(objects: &Path) -> Result<usize> {
    rustix::fs::sync();
    let mut count = 0;
    let mut pending = vec![objects.to_path_buf()];
    while let Some(dir) = pending.pop() {
        for entry in fs::read_dir(&dir)? {
            let entry = entry?;
            let kind = entry.file_type()?;
            if kind.is_dir() {
                pending.push(entry.path());
            } else if kind.is_file() {
                seal(&entry.path())?;
                count += 1;
            }
        }
    }
    Ok(count)
}

fn seal(path: &Path) -> Result<()> {
    let file = rustix::fs::open(path, OFlags::RDONLY | OFlags::CLOEXEC, Mode::empty())
        .with_context(|| format!("opening {}", path.display()))?;
    match fs_ioc_enable_verity(file.as_fd(), VERITY_SHA256, VERITY_BLOCK) {
        Ok(()) | Err(EnableVerityError::AlreadyEnabled) => Ok(()),
        Err(error) => bail!("fs-verity on {}: {error}", path.display()),
    }
}

/// The name hidestage maps the root under; see hidestage's unlock.rs.
const MAPPED_NAME: &str = "hideos-root";

/// Runs a tool with `input` on its standard input: how cryptsetup takes a
/// passphrase without a terminal.
fn with_stdin(command: &mut Command, input: &str) -> Result<()> {
    use std::io::Write;
    let mut child = command
        .stdin(std::process::Stdio::piped())
        .spawn()
        .with_context(|| format!("running {command:?}"))?;
    child
        .stdin
        .take()
        .context("no stdin")?
        .write_all(input.as_bytes())?;
    let status = child.wait()?;
    ensure!(status.success(), "{command:?} exited with {status}");
    Ok(())
}

/// A second keyslot, opened by `new`. cryptsetup takes both keys from
/// files here; they are in /run, memory, and removed after.
fn add_key(device: &Path, existing: &str, new: &str) -> Result<()> {
    use std::os::unix::fs::OpenOptionsExt;
    let dir = Path::new(WORK);
    fs::create_dir_all(dir)?;
    let write = |name: &str, text: &str| -> Result<PathBuf> {
        use std::io::Write;
        let path = dir.join(name);
        fs::OpenOptions::new()
            .write(true)
            .create(true)
            .truncate(true)
            .mode(0o600)
            .open(&path)?
            .write_all(text.as_bytes())?;
        Ok(path)
    };
    let old = write("key.old", existing)?;
    let fresh = write("key.new", new)?;
    let result = exec(
        tool("cryptsetup")
            .args(["luksAddKey", "--batch-mode", "--key-file"])
            .arg(&old)
            .arg(device)
            .arg(&fresh),
    );
    let _ = fs::remove_file(&old);
    let _ = fs::remove_file(&fresh);
    result
}

/// This machine's memory, in MiB.
pub(crate) fn memory_mib() -> Result<u64> {
    let meminfo = fs::read_to_string("/proc/meminfo")?;
    let kib: u64 = meminfo
        .lines()
        .find_map(|l| l.strip_prefix("MemTotal:"))
        .and_then(|v| v.trim().trim_end_matches("kB").trim().parse().ok())
        .context("no MemTotal in /proc/meminfo")?;
    Ok(kib.div_ceil(1024))
}

/// The first account, in @etc, with its home in @home.
fn add_user(root: &Path, name: &str, password: &str) -> Result<()> {
    let etc = root.join("@etc");
    let read = |file: &str| fs::read_to_string(etc.join(file)).unwrap_or_default();
    let files = hide::account::Files {
        passwd: read("passwd"),
        group: read("group"),
        shadow: read("shadow"),
    };
    let mut salt: hide::account::Salt = [0; 12];
    fs::File::open("/dev/urandom")
        .and_then(|mut f| f.read_exact(&mut salt))
        .context("reading /dev/urandom")?;
    let files = hide::account::add_first_user(&files, name, name, password, &salt)?;
    fs::write(etc.join("passwd"), files.passwd)?;
    fs::write(etc.join("group"), files.group)?;
    let shadow = etc.join("shadow");
    fs::write(&shadow, files.shadow)?;
    fs::set_permissions(&shadow, std::os::unix::fs::PermissionsExt::from_mode(0o600))?;

    // A reinstall finds the home already there: it is the account's again,
    // under the first user's id, which is the id it had.
    let home = root.join("@home").join(name);
    if !home.exists() {
        fs::create_dir(&home)?;
        fs::set_permissions(&home, std::os::unix::fs::PermissionsExt::from_mode(0o700))?;
    }
    let id = hide::account::FIRST_UID;
    rustix::fs::chown(
        &home,
        Some(rustix::fs::Uid::from_raw(id)),
        Some(rustix::fs::Gid::from_raw(id)),
    )?;
    Ok(())
}

pub(crate) fn mount_pseudo_filesystems() -> Result<()> {
    for (source, target, fstype) in [
        ("proc", "/proc", "proc"),
        ("sysfs", "/sys", "sysfs"),
        ("devtmpfs", "/dev", "devtmpfs"),
        ("tmpfs", "/run", "tmpfs"),
    ] {
        fs::create_dir_all(target)?;
        match mount(source, target, fstype, MountFlags::empty(), None) {
            Ok(()) | Err(rustix::io::Errno::BUSY) => {}
            Err(error) => return Err(error).with_context(|| format!("mounting {target}")),
        }
    }
    Ok(())
}

fn tool(name: &str) -> Command {
    let mut command = Command::new(name);
    command.env("PATH", PATH);
    command
}

fn exec(command: &mut Command) -> Result<()> {
    let status = command
        .status()
        .with_context(|| format!("running {:?}", command.get_program()))?;
    ensure!(status.success(), "{command:?} failed: {status}");
    Ok(())
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

fn say(line: &str) {
    eprintln!("hide install: {line}");
}
