[unit]
description = "PipeWire's session manager"
requires    = ["pipewire"]
after       = ["pipewire", "oxlogd"]

[service]
exec        = "/usr/bin/wireplumber"
restart     = "on-failure"
restart-sec = "1s"
output      = "log"
