[unit]
description = "System message bus"
requires    = ["oxlogd"]
after       = ["setup", "oxlogd"]

[service]
exec    = "/usr/bin/dbus-daemon --system --nofork --nopidfile"
restart = "on-failure"
output  = "log"
